import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CONTRACT_LABELS } from '@shared/types';
import { api } from '../api';
import { ContractIcon, cumulativeRows, Countdown, StatusPill } from '../components';
import { useLiveGame } from '../hooks';

const COLORS = ['#5b3df5', '#ff5d7a', '#10a87b', '#f0a61a', '#2e84e6', '#9b51e0', '#e15c2f', '#1b9aaa', '#704f32', '#65758b'];
export function GamePage() {
  const navigate = useNavigate();
  const [id, setId] = useState<string>(); const [adminToken, setAdminToken] = useState(''); useEffect(() => { api.active().then((value) => setId(value?.game.id)); api.adminSession().then((session) => setAdminToken(session.token)).catch(() => undefined); }, []); const { snapshot } = useLiveGame(id, 'display');
  if (!snapshot) return <div className="display-page center-stack"><h1>Tafaron</h1><p>En attente d’une partie…</p><Link to="/admin">Ouvrir l’admin</Link></div>;
  const { game, scores } = snapshot; const current = [...game.rounds].reverse().find((round) => round.status !== 'validated'); const chooser = game.players.find((p) => p.id === current?.chooserPlayerId); const ranking = [...game.players].sort((a, b) => scores[a.id] - scores[b.id]); const validatedCount = game.rounds.filter((round) => round.status === 'validated').length; const chart = [{ x: 0, ...Object.fromEntries(game.players.map((p) => [p.id, 0])) }, ...cumulativeRows(game)];
  const gameAction = async (path: string, body?: unknown) => { if (!adminToken) return; await api.admin(adminToken, `/api/games/${game.id}${path}`, 'POST', body); };
  const rechoose = async () => { if (!adminToken || !current?.chooserPlayerId) return; await gameAction('/round/rechoose', { playerId: current.chooserPlayerId }); navigate('/admin?from=game'); };
  return <div className="display-page"><header className="display-header"><div><span className="eyebrow">{game.name || 'Tafaron'}</span><h1>{game.status === 'finished' ? 'Partie terminée' : `${chooser?.name ?? '—'}, à toi !`}</h1><p className="contract-display">{current?.contract ? <><ContractIcon code={current.contract} className="contract-display-icon" /><strong>{current.contract === 'J' ? `Joker → ${CONTRACT_LABELS[current.jokerContract!]}` : CONTRACT_LABELS[current.contract]}</strong><small>({current.contract})</small></> : 'Choix du contrat en attente'}</p>{current?.status === 'in_progress' && <div className="display-actions"><button className="primary" disabled={!adminToken} onClick={() => void gameAction('/round/scoring')}>Calcul des points</button><button className="ghost" disabled={!adminToken} onClick={() => void rechoose()}>Revenir au choix</button></div>}</div><div className="round-counter"><strong>{snapshot.remainingRounds}</strong><span>manches restantes</span></div></header>{current?.status === 'countdown' && <Countdown endsAt={current.countdownEndsAt} />}
    <main className="display-grid"><section className="display-card chart-card"><h2>Évolution des scores</h2><ResponsiveContainer width="100%" height={350}><LineChart data={chart}><XAxis type="number" dataKey="x" domain={[0, Math.max(1, validatedCount)]} ticks={Array.from({ length: validatedCount + 1 }, (_, index) => index)} tickFormatter={(value) => value === 0 ? 'Départ' : `M${value}`} stroke="#8290ad" /><YAxis stroke="#8290ad" /><Tooltip labelFormatter={(value) => Number(value) === 0 ? 'Départ' : `Manche ${value}`} />{game.players.map((player, index) => <Line key={player.id} type="monotone" dataKey={player.id} name={player.name} stroke={COLORS[index % COLORS.length]} strokeWidth={4} dot={{ r: 4 }} />)}</LineChart></ResponsiveContainer></section><section className="display-card"><h2>Classement</h2><ol className="ranking large">{ranking.map((player, index) => <li key={player.id}><span><b>{index + 1}</b> {player.name}</span><strong>{scores[player.id]}</strong></li>)}</ol></section><section className="display-card matrix-card"><div className="section-head"><h2>Contrats</h2><StatusPill>{game.rounds.filter((r) => r.status === 'validated').length} joués</StatusPill></div><div className="matrix" style={{ gridTemplateColumns: `minmax(120px, 1.5fr) repeat(${game.settings.enabledContracts.length}, minmax(100px, 1fr))` }}><div />{game.settings.enabledContracts.map((code) => <strong title={CONTRACT_LABELS[code]} key={code}><ContractIcon code={code} className="matrix-contract-icon" />{CONTRACT_LABELS[code]}</strong>)}{game.players.map((player) => <div className="matrix-row" key={player.id}><strong>{player.name}</strong>{game.settings.enabledContracts.map((code) => { const round = game.rounds.find((r) => r.status === 'validated' && r.chooserPlayerId === player.id && r.contract === code); return <span className={round ? round.chooserSucceeded ? 'success' : 'failed' : ''} key={code}>{round ? round.contract === 'J' ? `Joker → ${CONTRACT_LABELS[round.jokerContract!]}` : round.chooserSucceeded ? '✓' : '○' : '·'}</span>; })}</div>)}</div></section></main><footer className="display-footer"><Link to="/admin?from=game">Retour admin</Link><Link to="/tables">Voir les tableaux complets</Link></footer></div>;
}
