import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api } from '../api';
import { ErrorBanner, StatusPill } from '../components';

export function HistoryPage() {
  const [games, setGames] = useState<Awaited<ReturnType<typeof api.games>>>([]); const [token, setToken] = useState(''); const [error, setError] = useState(''); const navigate = useNavigate();
  useEffect(() => { Promise.all([api.games(), api.adminSession()]).then(([list, session]) => { setGames(list); setToken(session.token); }).catch((reason) => setError(reason.message)); }, []);
  const activate = async (id: string) => { if (!confirm('Réactiver cette partie ? La partie active sera archivée.')) return; try { await api.admin(token, `/api/games/${id}/activate`); navigate('/admin'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Erreur.'); } };
  const remove = async (id: string, name?: string) => { if (!confirm(`Supprimer définitivement « ${name || 'Partie sans nom'} » ? Cette action est irréversible.`)) return; try { await api.admin(token, `/api/games/${id}`, 'DELETE'); setGames((current) => current.filter((game) => game.id !== id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Erreur.'); } };
  return <div className="app-shell"><header className="topbar"><div><span className="eyebrow">Sauvegardes locales</span><h1>Historique</h1></div><Link to="/admin">Retour admin</Link></header><ErrorBanner message={error} /><main className="history-list">{games.map((game) => <article className="panel history-card" key={game.id}><div><h2>{game.name || 'Partie sans nom'}</h2><p>{new Date(game.updatedAt).toLocaleString('fr-FR')} · {game.playerCount} joueurs</p></div><StatusPill tone={game.status === 'finished' ? 'good' : 'neutral'}>{game.status}</StatusPill><div className="row-actions"><a className="button" href={`/api/games/${game.id}/export/json`}>JSON</a><a className="button" href={`/api/games/${game.id}/export/scores.csv`}>Scores</a>{game.status === 'archived' ? <><button className="primary" onClick={() => activate(game.id)}>Réactiver</button><button className="danger ghost" onClick={() => remove(game.id, game.name)}>Supprimer</button></> : <button className="primary" onClick={() => activate(game.id)}>Réactiver</button>}</div></article>)}{!games.length && <p>Aucune partie sauvegardée.</p>}</main></div>;
}
