import { useCallback, useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { CONTRACT_LABELS, type EffectiveContractCode, type PlayerSubmission } from '@shared/types';
import { api, type PlayerView } from '../api';
import { ContractPicker, ErrorBanner, PersonalSubmissionForm, StatusPill } from '../components';
import { usePlayerRefresh } from '../hooks';

export function JoinPage() {
  const { gameId } = useParams(); const storageKey = `tafaron:${gameId}:token`; const [token, setToken] = useState(() => localStorage.getItem(storageKey) ?? ''); const [view, setView] = useState<PlayerView>(); const [name, setName] = useState(''); const [error, setError] = useState(''); const [editing, setEditing] = useState(false);
  const refresh = useCallback(() => { if (gameId && token) api.playerView(gameId, token).then((next) => { setView(next); if (!next.round?.hasSubmission) setEditing(false); }).catch((reason) => setError(reason.message)); }, [gameId, token]);
  useEffect(refresh, [refresh]); usePlayerRefresh(gameId, token, refresh);
  const join = async () => { if (!gameId) return; try { const result = await api.join(gameId, name); localStorage.setItem(storageKey, result.token); setToken(result.token); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Erreur.'); } };
  const act = async (path: string, body: unknown) => { if (!gameId || !token) return; try { await api.playerAction(gameId, token, path, body); setEditing(false); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Erreur.'); } };
  if (!token) return <div className="mobile-page"><div className="mobile-card"><div className="logo-mark">T</div><span className="eyebrow">Rejoindre Tafaron</span><h1>Quel est ton prénom&nbsp;?</h1><ErrorBanner message={error} /><input className="name-input" autoFocus maxLength={40} value={name} onChange={(e) => setName(e.target.value)} aria-label="Prénom" /><button className="primary huge" disabled={!name.trim()} onClick={join}>Rejoindre</button></div></div>;
  if (!view) return <div className="mobile-page"><div className="mobile-card"><p>Connexion à la partie…</p><ErrorBanner message={error} /></div></div>;
  const round = view.round; const effective = (round?.contract === 'J' ? round.jokerContract : round?.contract) as EffectiveContractCode | undefined;
  return <div className="mobile-page"><div className="mobile-card"><div className="mobile-head"><div><span className="eyebrow">Joueur</span><h1>{view.player.name}</h1></div><StatusPill tone={view.player.connected ? 'good' : 'neutral'}>connecté</StatusPill></div><ErrorBanner message={error} />
    {round?.isChooser && round.status === 'choosing' ? <><h2>C’est à toi de choisir</h2><ContractPicker options={round.contractOptions} available={round.availableContracts} used={round.usedContracts} onChoose={(contract, jokerContract) => act('contract', { contract, jokerContract })} /></>
    : round?.isChooser && round.status === 'in_progress' && round.contract ? <><span className="eyebrow">Contrat choisi</span><h2>{round.contract === 'J' ? `Joker → ${CONTRACT_LABELS[round.jokerContract!]}` : CONTRACT_LABELS[round.contract]}</h2><p>Tu peux lancer la saisie des résultats ou choisir un autre contrat.</p><button className="primary wide" onClick={() => act('scoring', {})}>Passer au calcul des points</button><button className="ghost wide" onClick={() => act('rechoose', {})}>Revenir au choix</button></>
    : round?.hasSubmission && round.canEditSubmission && editing && effective ? <><span className="eyebrow">{round.contract === 'J' ? `Joker → ${CONTRACT_LABELS[effective]}` : CONTRACT_LABELS[effective]}</span><h2>Modifier ma saisie</h2><PersonalSubmissionForm contract={effective} initial={round.submissionValues} maxHearts={round.maxHearts} maxQueens={round.maxQueens} maxTricks={round.maxTricks} submitLabel="Envoyer la correction" onSubmit={(values: PlayerSubmission['values']) => act('submission', values)} /><button className="ghost wide" onClick={() => setEditing(false)}>Annuler la modification</button></>
    : round?.needsSubmission && effective ? <><span className="eyebrow">{round.contract === 'J' ? `Joker → ${CONTRACT_LABELS[effective]}` : CONTRACT_LABELS[effective]}</span><h2>Saisis ton résultat</h2><PersonalSubmissionForm contract={effective} maxHearts={round.maxHearts} maxQueens={round.maxQueens} maxTricks={round.maxTricks} onSubmit={(values: PlayerSubmission['values']) => act('submission', values)} /></>
    : <div className="waiting-orbit"><div className="orbit"><span /></div><h2>{round?.hasSubmission ? 'Saisie envoyée !' : view.message}</h2>{round?.hasSubmission && round.canEditSubmission && <button className="primary" onClick={() => setEditing(true)}>Modifier ma saisie</button>}{round?.contract && <p>Contrat : {round.contract === 'J' ? `J → ${round.jokerContract}` : CONTRACT_LABELS[round.contract]}</p>}<small>Regarde l’écran principal pour suivre la partie.</small></div>}
  </div></div>;
}
